### PR TITLE
ActivityLog: added taxonomy messages to ActivityLogMessageParser

### PR DESCRIPTION
**Pull request by fefrain**

### CODE REVIEW

**Comment by gino-m** [comment]
@fefrain Did you add me intentionally? Not sure I have enough context to review, even if the Open Foris taxonomy data model is an old friend of mine :) Happy to reply to specific questions if you have them!

**Comment by fefrain** [comment]
> @fefrain Did you add me as reviewer on purpose? Not sure I have enough context to review, even if the Open Foris taxonomy data model is an old friend of mine :) Happy to reply to specific questions if you have them!

Sorry Gino! I've done it by mistake! I was looking for Mino... and you popped up...!

**Comment by gino-m** [comment]
> Sorry Gino! I've done it by mistake! I was looking for Mino... and you popped up...!

No worries at all! Happy to see things are moving along nicely!

**Comment by minotogna** [comment]
dai @gino-m , a @fefrain mancano i tuoi review... faglielo cmq ! =D =D

**Comment by gino-m** [comment]
> dai @gino-m , a @fefrain mancano i tuoi review... faglielo cmq ! =D =D

LGTM? 🤷‍♂

**Comment by minotogna** [comment]
> > dai @gino-m , a @fefrain mancano i tuoi review... faglielo cmq ! =D =D
> 
> LGTM?

=D thanks @gino-m an!

**Pull request merged**
